server:
  port: 9000

spring:
  application:
    name: demo

  #  datasource:
  #    platform: mysql
  #    url: jdbc:mysql://clone.ci1frsfm7h8y.ap-northeast-2.rds.amazonaws.com/COUPANG
  #    # url 형식은 jdbc:mysql://RDS의 EndPoint/내부 DB 스키마명 입니다.
  #    username: admin # 만약 따로 설정하지 않으셨다면 기본값은 admin 입니다
  #    password: password2848 # 비밀번호를 입력해주세요!
  #    driver-class-name: com.mysql.cj.jdbc.Driver



  datasource:
    platform: mysql
    url: jdbc:mysql://kys95db.cxbeukngkgwe.ap-northeast-2.rds.amazonaws.com/kys95DB
    # url 형식은 jdbc:mysql://RDS의 EndPoint/내부 DB 스키마명 입니다.
    username: admin # 만약 따로 설정하지 않으셨다면 기본값은 admin 입니다
    password: gmo3086* # 비밀번호를 입력해주세요!
    driver-class-name: com.mysql.cj.jdbc.Driver
